export const LOGIN_USER = "LOGIN_USER"
export const REGISTER_USER = "REGISTER_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const GET_LOGGEDIN_USER_DETAILS = "GET_LOGGEDIN_USER_DETAILS"

// Users Actions

export const GET_ALL_USERS = "GET_ALL_USERS"
export const CREATE_USER = "CREATE_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER"
export const GET_CURRENT_USER = "GET_CURRENT_USER"
export const GET_ALL_USERS_OF_MEMBER_ROLE = "GET_ALL_USERS_OF_MEMBER_ROLE"

// Expense Types Actions
export const GET_ALL_EXPSENSE_TYPES = "GET_ALL_EXPSENSE_TYPES"
export const CREATE_EXPSENSE_TYPES = "CREATE_EXPSENSE_TYPES"
export const UPDATE_EXPSENSE_TYPES = "UPDATE_EXPSENSE_TYPES"
export const DELETE_EXPSENSE_TYPES = "DELETE_EXPSENSE_TYPES"
export const GET_CURRENT_EXPENSE_TYPE = "GET_CURRENT_EXPENSE_TYPE"

// Household Actions

export const GET_ALL_HOUSEHOLDS = "GET_ALL_HOUSEHOLDS"
export const UPDATE_HOUSEHOLD = "UPDATE_HOUSEHOLD"
export const DELETE_HOUSEHOLD = "DELETE_HOUSEHOLD"
export const CREATE_HOUSEHOLD = "CREATE_HOUSEHOLD"
export const GET_CURRENT_HOUSEHOLD = "GET_CURRENT_HOUSEHOLD"
export const GET_ALL_HOUSEHOLDS_FOR_MEMBER = "GET_ALL_HOUSEHOLDS_FOR_MEMBER"

// Members Actions
export const GET_ALL_MEMBERS = "GET_ALL_MEMBERS"
export const CREATE_MEMBER = "CREATE_MEMBER"
export const UPDATE_MEMBER = "UPDATE_MEMBER"
export const DELETE_MEMBER = "DELETE_MEMBER"
export const GET_CURRENT_MEMBER = "GET_CURRENT_MEMBER"

//Periodic Payments
export const GET_ALL_PERIODIC_EXPENSE = "GET_ALL_PERIODIC_EXPENSE"
export const CREATE_PERIODIC_EXPENSE = "CREATE_PERIODIC_EXPENSE"
export const DELETE_PERIODIC_EXPENSE = "DELETE_PERIODIC_EXPENSE"
export const UPDATE_PERIODIC_EXPENSE = "UPDATE_PERIODIC_EXPENSE"
export const GET_CURRENT_PERIODIC_EXPENSE = "GET_CURRENT_PERIODIC_EXPENSE"


// Daily Expenses

export const GET_ALL_DAILY_EXPENSE = "GET_ALL_DAILY_EXPENSE"
export const CREATE_DAILY_EXPENSE = "CREATE_DAILY_EXPENSE"
// export const DELETE_DAILY_EXPENSE = "DELETE_DAILY_EXPENSE"
// export const UPDATE_DAILY_EXPENSE = "UPDATE_DAILY_EXPENSE"
export const GET_CURRENT_DAILY_EXPENSE = "GET_CURRENT_DAILY_EXPENSE"
export const GET_SPECIFIC_DAILY_EXPENSE = "GET_SPECIFIC_DAILY_EXPENSE"


export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION"
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION"
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS"

